version: '3'

services:
  backEnd:
    image: node:16
    container_name: exercise_api
    restart: always
    ports:
      - 3001:3001
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senha
      - MYSQL_DATABASE=exercicio23
      - MYSQL_HOST=db
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    tty: true # -t
    stdin_open: true #-i
    depends_on: 
      - db
  db:
    image: mysql:8.0.29
    container_name: exercise_mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha